### PR TITLE
Working on sending frames to p5 for BodyPix processing

### PR DESCRIPTION
**Pull request by shiffman**
Quick question before I keep going? Would I be better served by loading the image files from the client itself or is my methodology of loading using `fs` and sending as base64 via a message sound? 

```javascript
      const results = await unpackVideoToFrames(arg);
      // Hard coding one frame for now
      const imgb64 = fs.readFileSync('frames/out001.jpg', {
        encoding: 'base64'
      });
      event.reply('FRAMES_READY', imgb64);
```

### CODE REVIEW

**Comment by shiffman** [comment]
Ah this is a great idea, I will definitely take a look, thank you for sharing!!

**Comment by shiffman** [comment]
native-image worked great!

bodypix

**Comment by shiffman** [comment]
This is not complete but we could merge it in for continued work. To do's off the top of my head are:

* [ ] auto-detect canvas size (currently hard-coded)
* [ ] get total frames from FFMPEG and pass in (currently hard-coded)
* [ ] send each frame back to write to video file

I won't be able to return to this tomorrow so we can merge if anyone else wants to pick up where I left off.

**Comment by joeyklee** [comment]
@shiffman - let's merge in and we can work from where you've left off. I think I can resolve at least `auto-detect canvas size (currently hard-coded)`

**Comment by shiffman** [comment]
Great, just fixed a merge conflict let me make sure it still works and I will merge.

**Comment by shiffman** [comment]
Ok, merging!

**Comment by joeyklee** [comment]
🙏

**Pull request merged**
