### PR TITLE
Incorporating Face-API

### PR DESCRIPTION
**Pull request by shiffman**
@joeyklee I'm having trouble loading the face API models. I know you've worked with this before, any ideas?

```javascript
const faceapi = require("face-api.js");
const FACE_MODEL_URLS = {
  Mobilenetv1Model: "https://raw.githubusercontent.com/ml5js/ml5-data-and-models/face-api/models/faceapi/ssd_mobilenetv1_model-weights_manifest.json",
  TinyFaceDetectorModel: "https://raw.githubusercontent.com/ml5js/ml5-data-and-models/face-api/models/faceapi/tiny_face_detector_model-weights_manifest.json",
  FaceLandmarkModel: "https://raw.githubusercontent.com/ml5js/ml5-data-and-models/face-api/models/faceapi/face_landmark_68_model-weights_manifest.json",
  FaceLandmark68TinyNet: "https://raw.githubusercontent.com/ml5js/ml5-data-and-models/face-api/models/faceapi/face_landmark_68_tiny_model-weights_manifest.json",
  FaceRecognitionModel: "https://raw.githubusercontent.com/ml5js/ml5-data-and-models/face-api/models/faceapi/face_recognition_model-weights_manifest.json",
};

  // Load FaceAPI models
await faceapi.nets.ssdMobilenetv1.loadFromUri(FACE_MODEL_URLS.Mobilenetv1Model);
await faceapi.nets.tinyFaceDetector.loadFromUri(FACE_MODEL_URLS.TinyFaceDetectorModel);
```

Here's the error:

Screen Shot 2020-06-04 at 4 22 36 PM

```
/Users/shiffman/Documents/ml5/BodyBlock/node_modules/face-api.js/node_modules/@tensorflow/tfjs-core/dist/ops/tensor_ops.js:97 Uncaught (in promise) TypeError: engine_1.ENGINE.makeTensor is not a function
    at makeTensor (:9080/Users/shiffman/Documents/ml5/BodyBlock/node_modules/face-api.js/node_modules/@tensorflow/tfjs-core/src/ops/tensor_ops.ts:113)
    at Object.tensor (:9080/Users/shiffman/Documents/ml5/BodyBlock/node_modules/face-api.js/node_modules/@tensorflow/tfjs-core/src/ops/tensor_ops.ts:59)
    at _loop_2 (:9080/Users/shiffman/Documents/ml5/BodyBlock/node_modules/face-api.js/node_modules/@tensorflow/tfjs-core/src/io/io_utils.ts:175)
    at Object.decodeWeights (/Users/shiffman/Documents/ml5/BodyBlock/node_modules/face-api.js/node_modules/@tensorflow/tfjs-core/dist/io/io_utils.js:223)
    at :9080/Users/shiffman/Documents/ml5/BodyBlock/node_modules/face-api.js/node_modules/@tensorflow/tfjs-core/src/io/weights_loader.ts:236
    at Array.forEach (<anonymous>)
    at :9080/Users/shiffman/Documents/ml5/BodyBlock/node_modules/face-api.js/node_modules/@tensorflow/tfjs-core/src/io/weights_loader.ts:231
    at Array.forEach (<anonymous>)
    at :9080/Users/shiffman/Documents/ml5/BodyBlock/node_modules/face-api.js/node_modules/@tensorflow/tfjs-core/src/io/weights_loader.ts:212
    at step (/Users/shiffman/Documents/ml5/BodyBlock/node_modules/face-api.js/node_modules/@tensorflow/tfjs-core/dist/io/weights_loader.js:48)
```

### CODE REVIEW

**Comment by shiffman** [comment]
I think I fixed this by upgrading tfjs version. Hopefully I didn't break something else. More soon!

**Comment by shiffman** [comment]
The black rectangles are the secondary pass using tinyfaces:

faces

**Comment by joeyklee** [comment]
@shiffman - nice progress!

**Comment by shiffman** [comment]
@joeyklee this is at a stage where it can be merged. Needs more work of course but the basic functionality is there. I should also probably try more models. Apologies that my code formatting tracked lots of additional changes. I also couldn't get loading the local model files to work so I am using the ml5 repo urls.

**Pull request merged**
